
server:
  port: 62407
 
spring:
  datasource:
    username: root
    password: neusoft2020
    url: cd-cdb-q9ik8mug.sql.tencentcdb.com
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.neusoft.ecs.cm.model
 
#showSql
logging:
  level:
    com.neusoft.ecs: debug
