
server:
  port: 8080
 
spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3319/neuoa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.neusoft.oa.model
 
#showSql
logging:
  level:
    com.neusoft.oa.mapper : debug
